/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sskjellestad (https://sketchfab.com/sskjellestad)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/linen-with-flowers-91c24ace2e7d412493299f43dfa0061f
title: Linen with Flowers
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function LinenFlower(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/linen-flower.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.19, 18.75, -0.92]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.79, 0.79, 0.79]}
          >
            <group
              position={[-5.82, -9.17, -5.47]}
              rotation={[Math.PI / 2, -0.7, 0]}
              scale={[0.13, 0.3, 0.14]}
            >
              <mesh
                geometry={nodes["LinenwFlower_Material_#35_0"].geometry}
                material={nodes["LinenwFlower_Material_#35_0"].material}
              />
              <mesh
                geometry={nodes["LinenwFlower_Material_#36_0"].geometry}
                material={nodes["LinenwFlower_Material_#36_0"].material}
              />
            </group>
            <group
              position={[-5.82, -9.17, -5.47]}
              rotation={[Math.PI / 2, -0.7, 0]}
              scale={[0.13, 0.3, 0.14]}
            >
              <mesh
                geometry={nodes["LinenwFlower_M_Material_#35_0"].geometry}
                material={nodes["LinenwFlower_M_Material_#35_0"].material}
              />
              <mesh
                geometry={nodes["LinenwFlower_M_Material_#36_0"].geometry}
                material={nodes["LinenwFlower_M_Material_#36_0"].material}
              />
            </group>
            <group
              position={[-5.82, -9.17, -5.47]}
              rotation={[Math.PI / 2, -0.7, 0]}
              scale={[0.13, 0.3, 0.14]}
            >
              <mesh
                geometry={nodes["LinenwFlower_L_Material_#35_0"].geometry}
                material={nodes["LinenwFlower_L_Material_#35_0"].material}
              />
              <mesh
                geometry={nodes["LinenwFlower_L_Material_#36_0"].geometry}
                material={nodes["LinenwFlower_L_Material_#36_0"].material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/linen-flower.glb");
