/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fakepad (https://sketchfab.com/fakepad)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rose-fb1243f2843a4ba58ffae952b8275b91
title: Rose
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Rose(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/rose.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, -0.23, 0.18]}
            rotation={[0.17, -0.1, 0]}
            scale={[0.15, 0.15, 0.15]}
          >
            <mesh
              geometry={nodes.mesh_0.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/rose.glb");
